language: node_js
cache: yarn

matrix:
  include:
  - node_js: '12'
  - node_js: '10'
  - node_js: '8'
install:
  - yarn
  - yarn add global codecov
script:
  - yarn test
  - yarn lint
  - yarn build --sourcemap
after_success:
  - codecov -f ./coverage/coverage-final.json