language: node_js
cache: yarn

matrix:
  include:
  - node_js: '12'
  - node_js: '10'
  - node_js: '8'
install:
  - yarn
  - yarn add global codecov
  - yarn add global docusaurus-build
script:
  - yarn test
  - yarn lint
  - yarn build --sourcemap
  - cd docs/website && yarn build
after_success:
  - codecov -f ./coverage/coverage-final.json
# deploy:
#   - provider: github
#     skip_cleanup: true
#     keep_history: true
#     local_dir: docs/website/build/enotas
#     on:
#       branch: master